-- MySQL Script generated by MySQL Workbench
-- Mon Sep  4 22:36:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sadebb_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sadebb_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sadebb_ventas` DEFAULT CHARACTER SET utf8mb3 ;
USE `sadebb_ventas` ;

-- -----------------------------------------------------
-- Table `sadebb_ventas`.`sadebb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sadebb_ventas`.`sadebb_cliente` (
  `sadebb_idCliente` INT NOT NULL AUTO_INCREMENT,
  `sadebb_dni` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_direccion` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sadebb_idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 14473624
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sadebb_ventas`.`sadebb_detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sadebb_ventas`.`sadebb_detalle_ventas` (
  `sadebb_idDetalleVentas` INT NOT NULL,
  `sadebb_cantidad` INT NULL DEFAULT NULL,
  `sadebb_precioVenta` DOUBLE NULL DEFAULT NULL,
  `sadebb_ventas_sadebb_idVentas` INT NOT NULL,
  `sadebb_producto_sadebb_idProducto` INT NOT NULL,
  PRIMARY KEY (`sadebb_idDetalleVentas`),
  INDEX `fk_sadebb_detalle_Ventas_sadebb_ventas1_idx` (`sadebb_ventas_sadebb_idVentas` ASC) VISIBLE,
  INDEX `fk_sadebb_detalle_Ventas_sadebb_producto1_idx` (`sadebb_producto_sadebb_idProducto` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sadebb_ventas`.`sadebb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sadebb_ventas`.`sadebb_producto` (
  `sadebb_idProducto` INT NOT NULL AUTO_INCREMENT,
  `sadebb_codProducto` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_nombreProducto` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_stockProducto` INT NULL DEFAULT NULL,
  `sadebb_precioProducto` DOUBLE NULL DEFAULT NULL,
  `sadebb_estadoProducto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sadebb_idProducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sadebb_ventas`.`sadebb_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sadebb_ventas`.`sadebb_vendedor` (
  `sadebb_idVendedor` INT NOT NULL AUTO_INCREMENT,
  `sadebb_dni` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_nombre_vendedor` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_direccionVendedor` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_estadoVendedor` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_user` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sadebb_idVendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sadebb_ventas`.`sadebb_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sadebb_ventas`.`sadebb_ventas` (
  `sadebb_idVentas` INT NOT NULL,
  `sadebb_cliente_sadebb_idCliente` INT NOT NULL,
  `sadebb_vendedor_sadebb_idVendedor` INT NOT NULL,
  `sadebb_numeroVentas` VARCHAR(45) NULL DEFAULT NULL,
  `sadebb_fechaVentas` DATE NULL DEFAULT NULL,
  `sadebb_monto` DOUBLE NULL DEFAULT NULL,
  `sadebb_estadoVenta` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sadebb_idVentas`),
  INDEX `fk_sadebb_ventas_sadebb_cliente1_idx` (`sadebb_cliente_sadebb_idCliente` ASC) VISIBLE,
  INDEX `fk_sadebb_ventas_sadebb_vendedor1_idx` (`sadebb_vendedor_sadebb_idVendedor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
